<?php
require_once __DIR__ . '/../App/Core/Database.php';
require_once __DIR__ . '/../App/Seeder/UserSeeder.php';
require_once __DIR__ . '/../App/Seeder/RoleSeeder.php';
require_once __DIR__ . '/../App/Seeder/PermissionSeeder.php';
require_once __DIR__ . '/../App/Seeder/FeatureSeeder.php';
require_once __DIR__ . '/../App/Seeder/RolePermissionSeeder.php';
require_once __DIR__ . '/../App/Seeder/PermissionFeatureSeeder.php';
require_once __DIR__ . '/../App/Seeder/PostSeeder.php';
use App\Core\Database;
use App\Seeder\FeatureSeeder;
use App\Seeder\PermissionFeatureSeeder;
use App\Seeder\PermissionSeeder;
use App\Seeder\PostSeeder;
use App\Seeder\RolePermissionSeeder;
use App\Seeder\RoleSeeder;
use App\Seeder\UserSeeder;
// Run the seeder
$database = new Database();
$db = $database->getConnection();
// $roleSeeder = new RoleSeeder();
// $roleSeeder->run();
// $userSeeder = new UserSeeder();
// $userSeeder->run();
// $permissionSeeder = new PermissionSeeder();
// $permissionSeeder->run();
// $featureSeeder = new FeatureSeeder();
// $featureSeeder->run();
// $rolePermissionSeeder = new RolePermissionSeeder();
// $rolePermissionSeeder->run();
// $permissionFeatureSeeder = new PermissionFeatureSeeder();
// $permissionFeatureSeeder->run();
$postSeeder = new PostSeeder();
$postSeeder->run();